### ISSUE TITLE
S3 error: 'The "chunk" argument must be of type string or an instance of Buffer'

### ISSUE THREAD

**Issue by ebaizel** [ipfs/js-datastore-s3#38]
I'm trying to run the JS example in [examples/full-s3-repo](https://github.com/ipfs/js-datastore-s3/tree/master/examples/full-s3-repo) and getting the error below when I run `node index.js`:

```TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer. Received an instance of Uint8Array```

I haven't modified any of the code besides setting my Bucket and AccessKey/Secret. Running this with `node v14.18.0`.

**Comment by ebaizel** [comment]
Sure, here's the stack trace:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer. Received an instance of Uint8Array
    at new NodeError (internal/errors.js:322:7)
    at ClientRequest.end (_http_outgoing.js:811:13)
    at features.constructor.writeBody (/Users/baizele/workspace/git/js-datastore-s3/node_modules/aws-sdk/lib/http/node.js:141:14)
    at features.constructor.handleRequest (/Users/baizele/workspace/git/js-datastore-s3/node_modules/aws-sdk/lib/http/node.js:109:12)
    at executeSend (/Users/baizele/workspace/git/js-datastore-s3/node_modules/aws-sdk/lib/event_listeners.js:370:29)
    at Request.SEND (/Users/baizele/workspace/git/js-datastore-s3/node_modules/aws-sdk/lib/event_listeners.js:384:9)
    at Request.callListeners (/Users/baizele/workspace/git/js-datastore-s3/node_modules/aws-sdk/lib/sequential_executor.js:102:18)
    at Request.emit (/Users/baizele/workspace/git/js-datastore-s3/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/baizele/workspace/git/js-datastore-s3/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/baizele/workspace/git/js-datastore-s3/node_modules/aws-sdk/lib/request.js:22:10) {
  code: 'NetworkingError',
  region: 'us-east-1',
  hostname: abcbucket123.s3.amazonaws.com',
  retryable: true,
  time: 2021-10-13T13:20:33.708Z
}
```

**Comment by ebaizel** [comment]
I think I found the issue. This line `https://github.com/ipfs/js-datastore-s3/blob/master/examples/full-s3-repo/s3-lock.js#L72` needs to use `Buffer.from`. I got it working by replacing it with `Body: Buffer.from('')`. Does that sound right?
